# Generated by Django 3.1.5 on 2023-03-31 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={},
        ),
    ]
