server:
  port: 8081

spring:
  main:
    allow-bean-definition-overriding: true
  redis:
    host: j8e104.p.ssafy.io
    port: 6379
    password: cosmos104
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://j8e104.p.ssafy.io:3306/cosmos?useSSL=false&serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    username: root
    password: cosmos1234
#    url: jdbc:mysql://localhost:3306/cosmos?useSSL=false&serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
#    username: root
#    password: 1234
    hikari:
      pool-name: jpa-hikari-pool
      maximum-pool-size: 5
      jdbc-url: ${spring.datasource.url}
      username: ${spring.datasource.username}
      password: ${spring.datasource.password}
      driver-class-name: ${spring.datasource.driver-class-name}
      data-source-properties:
        rewriteBatchedStatements: true
  gson:
    date-format: YYYY-MM-dd HH:mm:ss
    field-naming-policy: lower_case_with_underscores
    serialize-nulls: false
  http:
    converters:
      preferred-json-mapper: gson

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        default_batch_fetch_size: 100
        order_inserts: true
        order_updates: true
        format_sql: true
cloud:
  aws:
    s3:
      bucket: cosmoss3
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: AKIASSX7K6T2I5UYR2ET
      secretKey: 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
logging:
  level:
    com:
      amazons:
        util:
          EC2MetadataUtils: error

