server:
  port: 8081

spring:
  redis:
    host: localhost
    port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://13.125.214.115:3306/tify?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    #username: rising88
    #password: Tify123!
    url: jdbc:mysql://localhost:3306/cosmos?useSSL=false&serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    username: root
    password: cosmos1234
    hikari:
      pool-name: jpa-hikari-pool
      maximum-pool-size: 5
      jdbc-url: ${spring.datasource.url}
      username: ${spring.datasource.username}
      password: ${spring.datasource.password}
      driver-class-name: ${spring.datasource.driver-class-name}
      data-source-properties:
        rewriteBatchedStatements: true

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        default_batch_fetch_size: ${chunkSize:100}
        jdbc.batch_size: 20
        order_inserts: true
        order_updates: true
        format_sql: true


#    <!--  transport.protocol">smtp</prop>
#    <prop key="mail.smtp.auth">true</prop>
#    <!-- gmail? ?? ???? ????? ?? SSLSocketFactory? ???? smtp ?? ??. -->
#    <prop key="mail.smtp.socketFactory.class">javax.net.ssl.SSLSocketFactory</prop>
#    <prop key="mail.smtp.starttls.enable">true</prop>
#    <prop key="mail.debug">true</prop>
#    <prop key="mail.smtp.ssl.trust">smtp.gmail.com</prop>



