# Generated by Django 3.1.5 on 2023-03-31 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0002_auto_20230331_1213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'managed': False},
        ),
    ]
